-- Truncate entity tables
TRUNCATE TABLE List CASCADE;
TRUNCATE TABLE Course CASCADE;
TRUNCATE TABLE Instructor CASCADE;
TRUNCATE TABLE Category CASCADE;
TRUNCATE TABLE Subcategory CASCADE;
TRUNCATE TABLE Topic CASCADE;

-- Truncate join tables
TRUNCATE TABLE Course_Instructor CASCADE;
TRUNCATE TABLE Course_Category CASCADE;
TRUNCATE TABLE Course_Subcategory CASCADE;
TRUNCATE TABLE Course_Topic CASCADE;
